variables:
  EXP_RUN_ARGS: ""
  AWS_ACCOUNT: 342840881361
  AWS_DEFAULT_REGION: us-east-1
  DVC_REMOTE_STORAGE_PUSH: s3://dvc-public/remote/cse/example-get-started-experiments/

# deploy-runner:
#   image: iterativeai/cml:0-dvc2-base1
#   script:
#   - pip install awscli
#   - >
#     CREDENTIALS=($(aws sts assume-role-with-web-identity
#     --region=${AWS_DEFAULT_REGION}
#     --role-arn=arn:aws:iam::${AWS_ACCOUNT}:role/SandboxUser
#     --role-session-name=GitLab
#     --duration-seconds=3600
#     --web-identity-token="$CI_JOB_JWT_V2"
#     --query="Credentials.[AccessKeyId,SecretAccessKey,SessionToken]"
#     --output=text))
#   - export AWS_ACCESS_KEY_ID="${CREDENTIALS[0]}"
#   - export AWS_SECRET_ACCESS_KEY="${CREDENTIALS[1]}"
#   - export AWS_SESSION_TOKEN="${CREDENTIALS[2]}"
#   - aws sts get-caller-identity
#   - >
#     cml runner launch --single \
#       --labels=cml \
#       --cloud=aws \
#       --cloud-region=us-east-1 \
#       --cloud-hdd-size=40 \
#       --cloud-type=g5.2xlarge

runner-job:
  needs:
    - deploy-runner
  tags:
    - cml
  image: iterativeai/cml:0-dvc2-base1
  script:
  # - pip install awscli
  # - >
  #   CREDENTIALS=($(aws sts assume-role-with-web-identity
  #   --region=${AWS_DEFAULT_REGION}
  #   --role-arn=arn:aws:iam::${AWS_ACCOUNT}:role/SandboxUser
  #   --role-session-name=GitLab
  #   --duration-seconds=3600
  #   --web-identity-token="$CI_JOB_JWT_V2"
  #   --query="Credentials.[AccessKeyId,SecretAccessKey,SessionToken]"
  #   --output=text))
  # - export AWS_ACCESS_KEY_ID="${CREDENTIALS[0]}"
  # - export AWS_SECRET_ACCESS_KEY="${CREDENTIALS[1]}"
  # - export AWS_SESSION_TOKEN="${CREDENTIALS[2]}"
  # - aws sts get-caller-identity
  - pip install -r requirements.txt
  - cml ci
  - dvc config --global studio.token $RUNNER_STUDIO_TOKEN
  - dvc exp run --allow-missing --force $EXP_RUN_ARGS 
  # - dvc remote add --local push_remote $DVC_REMOTE_STORAGE_PUSH
  # - dvc exp push origin -r push_remote
